name: Import TML to Single Org

on: 
  workflow_dispatch:
    inputs:
      OBJECT_TYPE:
        type: choice
        description: Type of Objects to Import
        options: 
        - DATA_MODEL
        - CONTENT
        - TABLE
        - MODEL
        - LIVEBOARD
        - ANSWER
        - CONNECTION
        required: true
      IMPORT_POLICY:
        type: choice
        description: Import Policy option of TML Import API
        options: 
        - ALL_OR_NONE
        - VALIDATE_ONLY
        - PARTIAL
        - PARTIAL_OBJECT
        required: true
      ASYNC:
        type: choice
        description: Sync or Async Import
        options:
          - SYNC
          - ASYNC
        required: true
      TS_ORG_NAME:
        type: string
        description: 'ThoughtSpot Org Name (not org_id) - override from environment'
        required: true
        default: '{None}'

permissions:
  contents: write

jobs:
  import_tml_single_org:

    runs-on: ubuntu-latest
    environment: |-
        ${{
           github.ref_name == 'release' && 'dev'
        || github.ref_name == 'dev' && 'dev'
        || github.ref_name == 'prod_deploy' && 'prod'
        || github.ref_name == 'prod' && 'prod'
        || github.ref_name == 'test_deploy' && 'test'
        || github.ref_name == 'test' && 'test'
        || github.ref_name == 'uat_deploy' && 'uat'
        || github.ref_name == 'uat' && 'uat'
        || 'default'
        }} 

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install thoughtspot_rest_api 
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Org_ID from Org_Name ${{ github.event.inputs.TS_ORG_NAME != '{None}' && github.event.inputs.TS_ORG_NAME || vars.TS_ORG_NAME }}
      env:
       TS_SERVER: ${{ secrets.TS_SERVER }}
       TS_SECRET_KEY: ${{ secrets.TS_SECRET_KEY }}
       TS_USERNAME: ${{ secrets.TS_INSTANCE_ADMIN_USERNAME }}
       TS_ORG_NAME: ${{ github.event.inputs.TS_ORG_NAME != '{None}' && github.event.inputs.TS_ORG_NAME || vars.TS_ORG_NAME }}
      run: |
         python .github/workflows/retrieve_org_id_from_org_name.py >> $GITHUB_ENV
         echo "$TS_ORG_NAME org_id retrieved"
    - name: Import TML to ThoughtSpot Org
      env:
       TS_SERVER: ${{ secrets.TS_SERVER }}
       TS_SECRET_KEY: ${{ secrets.TS_SECRET_KEY }}
       TS_USERNAME: ${{ secrets.TS_IMPORT_USERNAME }}
       OBJECT_TYPE: ${{ github.event.inputs.OBJECT_TYPE }}
       IMPORT_POLICY : ${{ github.event.inputs.IMPORT_POLICY }}
       ASYNC : ${{ github.event.inputs.ASYNC }}
      run: |
        echo "Import to Org_ID $ORG_ID of $OBJECT_TYPE using Import Policy: $IMPORT_POLICY"
        python .github/workflows/import_tml_to_org.py
